=== MiguelBarbosa04/PEI/marcacoes.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="marcacoes">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:byte" name="codMarcacao"/>
                <xs:element name="local">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="morada">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="cidade"/>
                                        <xs:element type="xs:string" name="codPostal"/>
                                        <xs:element type="xs:string" name="rua"/>
                                        <xs:element type="xs:short" name="porta"/>
                                        <xs:element name="coordenadas">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:float" name="latitude"/>
                                                    <xs:element type="xs:float" name="longitude"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="contactoCliente">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="nomePessoa"/>
                                        <xs:element type="xs:string" name="proprietario"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="contactoOficina">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="nomeEstabelicimento"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="veiculo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="marca"/>
                                        <xs:element type="xs:string" name="modelo"/>
                                        <xs:element type="xs:string" name="combustivel"/>
                                        <xs:element type="xs:string" name="transmissao"/>
                                        <xs:element type="xs:string" name="ano"/>
                                        <xs:element type="xs:short" name="potenciaCavalos"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MiguelBarbosa04/PEI/main/marcacoes.xml
<?xml version="1.0" encoding="UTF-8"?>
<m:marcacoes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="marcacoes.xsd marcacoes.xsd"
    xmlns:m="marcacoes.xsd"
    xmlns:l="local.xsd"
    xmlns:v="veiculo.xsd">

    <m:marcacao id="3">
        <!-- Número inteiro positivo-->
        <m:local>
            <l:morada>
                <l:cidade>Lixa</l:cidade>
                <l:codPostal>4615-594</l:codPostal> <!-- Pattern ZIP CODE -->
                <l:rua>Rua Doutor António Manuel Cerqueira Magro </l:rua>
                <l:porta>200</l:porta>
                <l:coordenadas>
                    <!-- Opcional-->
                    <l:latitude>41.324084</l:latitude>
                    <l:longitude>-8.145412</l:longitude>
                </l:coordenadas>
            </l:morada>

            <l:contacto type="Cliente">
                <!-- Pode ser cliente ou oficina-->
                <l:nome>Miguel</l:nome>
                <l:proprietario>Yes</l:proprietario> <!-- Yes ou No-->
            </l:contacto>

<!--ADIICIONAR <per:dia>1/1/2020</per:dia> e por no peritagem.xsd
            <per:horaInicio>23:24</per:horaInicio>
            <per:horaFim>15:00</per:horaFim> -->

        </m:local>

        <m:veiculo>
            <v:marca>BMW</v:marca>
            <v:modelo>i4</v:modelo>
            <v:combustivel>Eletric</v:combustivel> <!-- Tem opções "Diesel", "Gasoline", "Eletric/Gasoline" ou "Eletric"-->
            <v:transmissao>Auto</v:transmissao> <!-- "Auto" ou "Manual"-->
            <v:ano>2020</v:ano>
            <v:potencia>200</v:potencia>
        </m:veiculo>

    </m:marcacao>
</m:marcacoes>
